name: ecommerce_int2
description: It is about a complete ecommerce app for Android and iOS.

version: 1.0.1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #--- Views ---#
  cupertino_icons: ^1.0.5
  go_router: ^14.2.7
  flutter_svg: ^2.0.10+1
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  #fluttertoast: ^8.2.2
  card_swiper: ^3.0.1
  rubber: ^1.1.0
  google_fonts: ^6.2.1
  transparent_image: ^2.0.1
  image_picker: ^1.0.4
  syncfusion_flutter_datepicker: ^28.2.3
  fluttertoast: ^8.1.1


  #--- Network & Storage ---#
  http: ^1.2.2
  intl: ^0.20.2
  # contacts_service: ^0.6.3
  json_annotation: ^4.8.1
  path_provider: ^2.0.15
  dio: ^5.3.2
  shared_preferences: ^2.2.1
  


  #--- Map & Storage ---#
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  google_maps_flutter: ^2.4.0
  flutter_polyline_points: ^2.1.0

  #--- Helper ---#
  permission_handler: ^11.3.1
  country_code_picker: ^3.0.0
  pin_code_text_field: ^1.8.0
  numberpicker: ^2.1.2
  logger: ^2.0.1
  flutter_easyloading: ^3.0.5
  get: ^4.6.6
  
  #-- PhonePe --#
  get_it: ^8.0.0
  # phonepe_payment_sdk: ^3.0.0
  crypto: ^3.0.3
  provider: ^6.1.2


  #flare_splash`_screen: ^4.0.0
  #app_upgrade_flutter_sdk: ^2.0.0
  #flutter_upgrader: ^1.0.7
  #location: ^5.0.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.14.3

  
 

  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/shopeLogo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/promotional/
    - assets/myproduct/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf
